exp: 
  name: 'baseline'
  desc: ''
  epochs: 5

model:
  batch_size: 256
  voc_len: 20_000
  emb_dim: 128
  seq_len: 10_000
  dropout: 0.5
  strides: 3
  frames: 
    - 2
    - 3
    - 4
    - 5
    - 6