exp: 
  name: 'ConvNet5P'
  desc: '5 parallel convolutional layers aggregated with a DNN before passing throught the output layer'
  epochs: 5
  batch_size: 256

corpus:
  voc_len: 20_000
  seq_len: 1_000
  emb_dim: 128

model:
  dropout: 0.3
  num_filters: 64 
  convs:
    # Defining 5 parallel convolutionnal networks
    - kernel: 2
      strides: 1
    - kernel: 3
      strides: 1
    - kernel: 4
      strides: 1
    - kernel: 5
      strides: 1
    - kernel: 6
      strides: 1
  fc_dim: 256
  loss: 'categorical_crossentropy'
  optimizer: 'nadam'
  metrics: 
    - 'accuracy'